// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACnTas9D62NqOAn2kQYmF4naEXrB_nfgQ',
    appId: '1:884852658015:web:ca08c10aafec1a1cabf0ea',
    messagingSenderId: '884852658015',
    projectId: 'sign-up-93705',
    authDomain: 'sign-up-93705.firebaseapp.com',
    databaseURL: 'https://sign-up-93705-default-rtdb.firebaseio.com',
    storageBucket: 'sign-up-93705.firebasestorage.app',
    measurementId: 'G-Z0KWLRJVW2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpOlKN_M_EPeTcr7KLyb6sq4-DgE3d_yE',
    appId: '1:884852658015:android:b364ad78425e4943abf0ea',
    messagingSenderId: '884852658015',
    projectId: 'sign-up-93705',
    databaseURL: 'https://sign-up-93705-default-rtdb.firebaseio.com',
    storageBucket: 'sign-up-93705.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtYs795s5B7qf9cR2kQSKTCHcOWkBjdGs',
    appId: '1:884852658015:ios:c50f2f9ec79b1037abf0ea',
    messagingSenderId: '884852658015',
    projectId: 'sign-up-93705',
    databaseURL: 'https://sign-up-93705-default-rtdb.firebaseio.com',
    storageBucket: 'sign-up-93705.firebasestorage.app',
    iosBundleId: 'com.example.helloworld',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtYs795s5B7qf9cR2kQSKTCHcOWkBjdGs',
    appId: '1:884852658015:ios:c50f2f9ec79b1037abf0ea',
    messagingSenderId: '884852658015',
    projectId: 'sign-up-93705',
    databaseURL: 'https://sign-up-93705-default-rtdb.firebaseio.com',
    storageBucket: 'sign-up-93705.firebasestorage.app',
    iosBundleId: 'com.example.helloworld',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyACnTas9D62NqOAn2kQYmF4naEXrB_nfgQ',
    appId: '1:884852658015:web:f9e6c827d8b38be3abf0ea',
    messagingSenderId: '884852658015',
    projectId: 'sign-up-93705',
    authDomain: 'sign-up-93705.firebaseapp.com',
    databaseURL: 'https://sign-up-93705-default-rtdb.firebaseio.com',
    storageBucket: 'sign-up-93705.firebasestorage.app',
    measurementId: 'G-C0EPDBMC6V',
  );
}
